### ISSUE TITLE
Calculation of absorption

### ISSUE THREAD

**Issue by me-astro** [me-manu/blrabsorption#1]
Hi,

Thank you for this nice script.
can you please advice using this script how the absorption versus energy can be calculated for a given distance from the central black hole?

Thanks in advance

**Comment by me-manu** [comment]
Hi @me-astro, 

Sorry for not providing any decent documentation or examples. I had not thought so far about actually releasing the code but it's probably a good thing to do in the future. 

Below I provide an example how to calculate the optical depth as a function of energy and distance to the supermassive black hole (energy is in the galaxy frame) for 3C279: 

```
from blrabsorption import absorption as ab

LHbeta = 1.728e43 # ergs / s from Liu et al. 2006, Table 1 and Eq. 7
M_BH = np.power(10.,8.28) # in solar masses from Liu et al. 2006, Table 1
z = 0.536

Ldisk = np.power(10.,12.32 + 0.78 * np.log10(LHbeta)) # from Eq. 9 in Zamaninasab et al. 2014
blr = ab.BLR(Ldisk, z,  lumiHbeta = LHbeta, M_BH = M_BH)

idx = blr.blr_lines['Ion'] == 'Ly alpha'
RLyalpha = blr.Rli[idx][0]
print ("RLyalpha = {0:.2e} cm".format(RLyalpha))

#geometry = 'Shell'
geometry = 'Ring'

EGeV = np.logspace(0.,3.,100) # in galaxy frame!
Rcm = np.logspace(-1.,1.5,51) * RLyalpha

tau = blr.tau(EGeV, Rcm, 
                    geometry = geometry,
                    lsteps = 100, mu_steps=100, 
                    rtilde_max = 1e12
                   )
```
Hope this helps!

**Comment by me-astro** [comment]
Thanks a lot for your help!
Just another question Rcm is the size of the emitting region right ? or it is the distance from BH ?
tau function defined above is the absorption between 1-1000 GeV, calculated for distances 0.1 RLyalpha, 0.112 RLyalpha, 0.12589254 RLyalpha..... right ?

Many thanks!

**Comment by me-manu** [comment]
Rcm is the distance to the BH. And yes the absorption is then calculated for these energies and distances for each emission line, that's why you will get in the end an array with three axes. To get the total optical depth you would then sum over the last axis, i.e., `tau_tot = tau.sum(axis = -1)`

**Comment by me-manu** [comment]
Oh and by the way, if you are using the code for a publication, I'd be grateful if you could cite our paper where we first used it (currently under review at ApJ): https://arxiv.org/abs/1902.02291

**Comment by me-astro** [comment]
Thanks a lot!
of course, I know the paper which you mentioned and I like it very much :).
I will definitely cite it.
